exclude: ^.idea/$
repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: docs
    -   id: end-of-file-fixer
        exclude: docs
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-toml
    -   id: check-ast
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: check-vcs-permalinks
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        exclude: docs
        types:
        - python
        args: [--multi-line=3, --trailing-comma, --line-length="99",--ignore= E722]
    -   id: black
        name: black
        entry: black
        language: system
        exclude: docs
        types:
        - python
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        exclude: docs
        types:
        - python
        args: [--max-line-length="99",--ignore= E722]
#    -   id: pydocstyle
#        name: pydocstyle
#        entry: pydocstyle
#        language: system
#        exclude: docs
#        types:
#        - python
