FROM python:3.7-slim
COPY pyproject.toml poetry.lock ./
RUN apt update && apt install -y curl apt-utils
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
RUN POETRY_VIRTUALENVS_CREATE=false $HOME/.poetry/bin/poetry install --no-dev
COPY ./src/prediction_server /app

WORKDIR /app
EXPOSE 5000

# Define environment variable
ENV MODEL_NAME DetectFaceClassifyMask
ENV API_TYPE REST
ENV SERVICE_TYPE MODEL
ENV PERSISTENCE 0

CMD exec seldon-core-microservice $MODEL_NAME $API_TYPE --service-type $SERVICE_TYPE --persistence $PERSISTENCE
